### PR TITLE
v0.11.0

### PR DESCRIPTION
**Pull request by flavioislima**
v0.11.0

### CODE REVIEW

**Comment by barthalion** [comment]
Hi Flavio, this is primarily failing because of the weirdly formatted appdata XML file, specifically name and ID fields having a bunch of whitespace inside tags: https://github.com/flathub/xyz.hyperplay.HyperPlay/blob/master/xyz.hyperplay.HyperPlay.metainfo.xml#L2

We're dropping the other two checks it has triggered, but it will take a few hours to propagate.

**Comment by barthalion** [comment]
That being said, you will also need developer name to the file.

**Comment by flavioislima** [comment]
> Hi Flavio, this is primarily failing because of the weirdly formatted appdata XML file, specifically name and ID fields having a bunch of whitespace inside tags: https://github.com/flathub/xyz.hyperplay.HyperPlay/blob/master/xyz.hyperplay.HyperPlay.metainfo.xml#L2
> 
> We're dropping the other two checks it has triggered, but it will take a few hours to propagate.

HI! Thanks for the heads up, I will fix those.

The formatting is weird because we have an automated workflow that generates it, I will check if we can fix it as well. For now, I will fix it manually,

**Comment by flavioislima** [comment]
bot, build

**Pull request merged**
